routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();
Route::group(['middleware' => 'auth','prefix' => 'dashboard'], function(){

    Route::get('/links','LinkController@index');
    Route::get('/links/new','LinkController@create');
    Route::post('/links/new','LinkController@store');
    Route::get('/links/{link}','LinkController@edit');
    Route::post('/links/{link}','LinkController@update');
    Route::delete('/links/{link}','LinkController@destroy');

    Route::get('/settings','UserController@edit');
    Route::post('/settings','UserController@update');

});

Route::post('/visit/{link}','VisitController@store');

//linktree.test/username
Route::get('/{user}','UserController@show');

Route::get('/home', 'HomeController@index')->name('home');

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $guarded=[];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function visits(){
        return $this->hasMany(Visit::class);
    }

    public function latest_visit(){
        return $this->hasOne(Visit::class)->latest();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'username',
        'email',
        'password',
        'background_color',
        'text_color',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function links()
    {
        return $this->hasMany(Link::class);
    }

    public function visits(){
        $this->hasManyThrough(Visit::class,Link::class ); //pokazimigi samo visits samo za toj user za  toj link
    }

    public function getRouteKeyName()//OVA GO KLAVAME KAKO ZA SLUG DA MOZI DA LINKTTREE.TEST/MARKOSKI97 DA PREBARUVA MESTO LINKTREEE.TEST/1
    {
        return 'username';
    }
}

app/Visit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Visit extends Model
{
    protected $guarded=[];

    public function link(){
        return $this->belongsTo(Link::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LinkController extends Controller
{

    public function index()
    {
        $links=Auth::user()->links()
            ->withCount('visits')
            ->with('latest_visit')
            ->get();
       return view('links.index',compact('links'));
    }

    public function create()
    {
       return view('links.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'link' => 'required|url'
        ]);

        $link = Auth::user()->links()
            ->create($request->only(['name', 'link']));

        if ($link) {
            return redirect()->to('/dashboard/links');
        }

        return redirect()->back();
    }


    public function edit(Link $link)
    {
        if ($link->user_id !== Auth::id()) {
            return abort(404);
        }//Ako Linko ne pripaga na usero daj mu 404 (Ako si smeni nekoj sam id vo url)
        return view('links.edit',compact('link'));
    }


    public function update(Request $request,Link $link)
    {
        if ($link->user_id !== Auth::id()) {
            return abort(403);
        }//Ako Linko ne pripaga na usero daj mu 404 (Ako si smeni nekoj sam id vo url)

        $request->validate([
            'name' => 'required|max:255',
            'link' => 'required|url'
        ]);

       $link->update($request->only(['name','link']));

       return redirect()->to('/dashboard/links');
    }

    public function destroy(Link $link)
    {
        if ($link->user_id !== Auth::id()) {
            return abort(403);
        }//Ako Linko ne pripaga na usero daj mu 404 (Ako si smeni nekoj sam id vo url)

        $link->delete();
        return redirect()->to('/dashboard/links');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{

    public function edit()
    {
        $user=Auth::user();
        return view ('users.edit',compact('user'));
    }

    public function update(Request $request)
    {
        $request->validate([
            'background_color' =>'required|size:7|starts_with:#',
            'text_color' =>'required|size:7|starts_with:#',
        ]);

        Auth::user()->update($request->only(['background_color','text_color']));

        return redirect()->back();
    }

    public function show(User $user)
    {
        return view('users.show',compact('user'));
    }
}

app/Http/Controllers/VisitController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use Illuminate\Http\Request;

class VisitController extends Controller
{

    public function store(Request $request,Link $link)
    {
        return $link->visits()
            ->create([
                'user_agent'=>$request->userAgent()
            ]);
    }


}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'LinkTree') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'LinkTree') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->username }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/dashboard/settings">Settings</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/links.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app" style="background: {{$user->background_color}}">

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/links/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 card">
                <div class="card-body">
                    <h2 class="card-title">Create a new link</h2>
                    <form action="/dashboard/links/new" method="post">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="name">Link Name</label>
                                    <input type="text" id="name" name="name"
                                           class="form-control {{$errors->first('name') ? 'is-invalid' : ''}}"
                                           placeholder="Your Link Name" value="{{old('name')}}">
                                    @if($errors->first('name'))
                                        <div class="invalid-feedback">{{$errors->first('name')}}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="link">Link URL</label>
                                    <input type="text" id="link" name="link" class="form-control {{$errors->first('link')? 'is-invalid': ''}}"
                                           placeholder="Your Url" value="{{old('link')}}">
                                    @if($errors->first('link'))
                                        <div class="invalid-feedback">{{$errors->first('link')}}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                @csrf
                                <button type="submit" class="btn btn-primary">Save Link</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/links/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 card">
                <div class="card-body">
                    <h2 class="card-title">Create a new link</h2>
                    <form action="/dashboard/links/{{$link->id}}" method="post">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="name">Link Name</label>
                                    <input type="text" id="name" name="name"
                                           class="form-control {{$errors->first('name') ? 'is-invalid' : ''}}"
                                           placeholder="Your Link Name" value="{{$link->name}}">
                                    @if($errors->first('name'))
                                        <div class="invalid-feedback">{{$errors->first('name')}}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="link">Link URL</label>
                                    <input type="text" id="link" name="link"
                                           class="form-control {{$errors->first('link')? 'is-invalid': ''}}"
                                           placeholder="Your Url" value="{{$link->link}}">
                                    @if($errors->first('link'))
                                        <div class="invalid-feedback">{{$errors->first('link')}}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                @csrf
                                <button type="submit" class="btn btn-primary">Save Link</button>
                                <button type="button" class="btn btn-secondary"
                                        onclick="event.preventDefault();
                                        document.getElementById('delete-form').submit();">Delete
                                </button>
                            </div>
                        </div>
                    </form>
                    <form action="/dashboard/links/{{$link->id}}" method="post" id="delete-form">
                        @csrf
                        @method('DELETE')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/links/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-12 card">
            <div class="card-body">
                <h2 class="card-title">
                    Your Links
                </h2>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Url</th>
                        <th>Visits</th>
                        <th>Last Visited Date</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($links as $link)
                        <tr>
                            <td>{{$link->name}}</td>
                            <td><a href="{{$link->link}}">{{$link->link}}</a></td>
                            <td>{{$link->visits_count}}</td>
                            <td>{{$link->latest_visit ? $link->latest_visit->created_at->format('M j Y - H:ia'): 'N/A'}}</td>
                            <td><a href="/dashboard/links/{{$link->id}}">Edit</a> </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <a href="/dashboard/links/new" class="btn btn-primary">Add new Link </a>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 card">
                <div class="card-body">
                    <h2 class="card-title">Settings</h2>
                    <form action="/dashboard/settings" method="post">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="background_color">Background Color</label>
                                    <input type="text" id="background_color" name="background_color"
                                           class="form-control {{$errors->first('background_color') ? 'is-invalid' : ''}}"
                                           placeholder="#fffffff" value="{{$user->background_color}}">
                                    @if($errors->first('background_color'))
                                        <div class="invalid-feedback">{{$errors->first('background_color')}}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="text_color">Text Color</label>
                                    <input type="text" id="text_color" name="text_color"
                                           class="form-control {{$errors->first('text_color')? 'is-invalid': ''}}"
                                           placeholder="#000000000" value="{{$user->text_color}}">
                                    @if($errors->first('text_color'))
                                        <div class="invalid-feedback">{{$errors->first('text_color')}}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                @csrf
                                <button type="submit" class="btn btn-primary">Save Settings</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.links')
@section('content')
        <div class="container py-4">
            <div class="row">
                <div class="col-12 col-md-6 offset-3">
                    @foreach($user->links as $link)
                        <div class="link">
                            <a
                                href="{{$link->link}}" class="user-link d-block p-4 mb-4 rounded h3 text-center"
                                data-link-id="{{$link->id}}"
                                target="_blank" rel="nofollow"
                                style="border: 2px solid {{$user->text_color}};color:{{$user->text_color}}"
                            >{{$link->name}}</a>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
@endsection